# Generated by Django 4.0.6 on 2022-11-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_enrollment_faculty_subject_subjectrating_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
