# Generated by Django 4.0.6 on 2022-11-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_category_table_alter_course_table'),
    ]

    operations = [
    ]
